repos:
  - repo: https://github.com/peterdemin/pip-compile-multi
    rev: v2.4.1
    hooks:
      - id: pip-compile-multi-verify

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: flake8
      - id: trailing-whitespace
